### ISSUE TITLE
No matches for wildcard

### ISSUE THREAD

**Issue by anki-code** [xxh/xxh-shell-fish#10]
```
~/.xxh/shells/xxh-shell-fish/build/xxh-config.fish (line 1): No matches for wildcard '$CURRENT_DIR/../../../plugins/*-fish-*/build'. See `help expand`.
find $CURRENT_DIR/../../../plugins/*-fish-*/build -type f -name '*pluginrc.fish' -printf '%f\t%p\n' 2>/dev/null | sort -k1 | cut -f2
     ^
in command substitution
        called on line 6 of file ~/.xxh/shells/xxh-shell-fish/build/xxh-config.fish
```

**Comment by anki-code** [comment]
@frederickjh please take a look. This message appears when using fish without plugins. Looks like the wildcard just empty [on line 6](https://github.com/xxh/xxh-shell-fish/blob/master/xxh-config.fish#L6). Is there a way to suppress the message?

**Comment by frederickjh** [comment]
I think that you will need to use a similar `find` statement to the one you currently have, to test if there are any plugin files in an `if` statement that checks to see if there are any plugins before running it runs the `for` loop.
