### ISSUE TITLE
Add xxh-config.fish rc file with plugins init/import/source code

### ISSUE THREAD

**Issue by frederickjh** [xxh/xxh-shell-fish#4]
This will allow plugins to be developed for [xxh/xxh-shell-fish](https://github.com/xxh/xxh-shell-fish), then they will be initialized and imported at shell start.

**Comment by anki-code** [comment]
@frederickjh am I right you'll do it? Or you're waiting it from me :)

**Comment by frederickjh** [comment]
I am going to work on it. I just can't assign it to myself, as I don't have permission to. Life got  busy today away from the computer.

**Comment by anki-code** [comment]
Thanks!
